# Generated by Django 4.1.11 on 2024-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_app', '0002_rename_username_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('enquiry', models.CharField(blank=True, choices=[('BUY', 'Buy a House'), ('RENT', 'Rent a House'), ('VISIT', 'Visit a House'), ('AGENT', 'Contact Agent'), ('INFORMATION', 'Information About Locations')], default='', max_length=50, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=400, null=True)),
            ],
        ),
    ]
