# Generated by Django 4.1.11 on 2024-02-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_app', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='unknown', max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='user', max_length=150),
        ),
    ]
