# Generated by Django 4.1.11 on 2024-01-03 22:10

import Eco_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('content', models.TextField(blank=True, default='', max_length=2500, null=True)),
                ('image', models.ImageField(upload_to=Eco_blog.models.blog_directory_path)),
                ('author', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_bloged', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
