# Generated by Django 4.1.11 on 2024-01-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(blank=True, default='', max_length=2500, null=True, serialize=False),
        ),
    ]
