# Generated by Django 4.1.11 on 2023-12-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_location', models.CharField(max_length=20, verbose_name='City')),
                ('home_location', models.CharField(max_length=100, verbose_name='Home Location')),
                ('home_type', models.CharField(blank=True, choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent')], max_length=30, null=True)),
                ('beds_rooms', models.IntegerField(verbose_name='Bed Rooms')),
                ('bath_rooms', models.IntegerField(verbose_name='Bath Rooms')),
                ('sqft', models.IntegerField(verbose_name='Square feet')),
                ('price', models.IntegerField(verbose_name='Home Price')),
                ('image', models.ImageField(upload_to='homes/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('home', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='Eco_home.home')),
            ],
        ),
    ]
