# Generated by Django 4.1.11 on 2024-01-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_home', '0002_alter_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateField()),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
