# Generated by Django 4.1.11 on 2024-01-01 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eco_home', '0003_tourrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
