# Generated by Django 4.1.11 on 2024-01-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eco_home', '0004_tourrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourrequest',
            name='home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tour_requests_home', to='Eco_home.home'),
        ),
    ]
