# Generated by Django 4.1.11 on 2024-01-02 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Eco_home', '0006_alter_tourrequest_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrequest',
            name='home',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tour_requests_home', to='Eco_home.home'),
        ),
        migrations.AlterField(
            model_name='tourrequest',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tour_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
